import { Review } from "./types";

/**
 * Avis vérifiés fournis par Maison Loravie pour "Ventilateur Anti-Mouches de Table"
 * (export Excel du système d'avis, achats réellement vérifiés).
 */
export const ventilateurAntiMouchesReviews: Review[] = [
  {
    id: "avis-vam-1",
    author: "Sacha",
    rating: 5,
    date: "2026-01-05",
    title: "Très pratique",
    body: "Facile à poser au milieu de la table et simple à utiliser.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-2",
    author: "Laura",
    rating: 5,
    date: "2026-07-05",
    title: "Très pratique",
    body: "Bon accessoire pour les repas d'été, il fait le travail attendu.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-3",
    author: "Alice",
    rating: 5,
    date: "2026-01-09",
    title: "Satisfait de l'utilisation",
    body: "Le mouvement des pales semble éloigner les insectes sans gêner le repas.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-4",
    author: "Victor",
    rating: 5,
    date: "2026-07-30",
    title: "Très pratique",
    body: "Design discret et utilisation intuitive.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-5",
    author: "David",
    rating: 5,
    date: "2026-09-03",
    title: "Très pratique",
    body: "Après essai : utile pour le déjeuner dehors, surtout quand il y à des fruits sur la table.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-6",
    author: "Océane",
    rating: 4,
    date: "2026-01-17",
    title: "Plutôt satisfait",
    body: "Utile pendant les repas, mais l'efficacité varie selon les conditions.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-7",
    author: "Antoine",
    rating: 5,
    date: "2026-03-19",
    title: "Simple à utiliser",
    body: "Installation rapide, pas besoin d'un montage compliqué.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-8",
    author: "Jonathan",
    rating: 5,
    date: "2026-02-14",
    title: "Très pratique",
    body: "Format adapté à une table de jardin.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-9",
    author: "Paul",
    rating: 5,
    date: "2026-06-10",
    title: "Utile pendant les repas",
    body: "Une idée pratique pour limiter les mouches autour des plats.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-10",
    author: "Alex",
    rating: 5,
    date: "2026-07-12",
    title: "Utile pendant les repas",
    body: "À noter : il prend peu de place et se déplace facilement.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-11",
    author: "Amélie",
    rating: 5,
    date: "2026-03-31",
    title: "Satisfait de l'utilisation",
    body: "Bon petit accessoire pour les repas en plein air.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-12",
    author: "Charlotte",
    rating: 5,
    date: "2026-02-05",
    title: "Utile pendant les repas",
    body: "Utilisation simple : on le pose et on l'allume.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-13",
    author: "Ilyas",
    rating: 4,
    date: "2026-01-15",
    title: "Plutôt satisfait",
    body: "Aide à éloigner les mouches, mais ne remplace pas les autres précautions.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-14",
    author: "Léonie",
    rating: 5,
    date: "2026-08-23",
    title: "Simple à utiliser",
    body: "Le produit correspond à ce que j'attendais.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-15",
    author: "Mathilde",
    rating: 5,
    date: "2026-03-27",
    title: "Satisfait de l'utilisation",
    body: "Mon impression : une solution facile à essayer pendant la saison des mouches.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-16",
    author: "Charlotte",
    rating: 5,
    date: "2026-06-29",
    title: "Satisfait de l'utilisation",
    body: "J'apprécie de pouvoir le placer près des plats sans utiliser de produit répulsif.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-17",
    author: "Amélie",
    rating: 5,
    date: "2026-07-12",
    title: "Utile pendant les repas",
    body: "Fonctionne mieux quand il est placé au centre de la table.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-18",
    author: "Jade",
    rating: 5,
    date: "2026-05-24",
    title: "Satisfait de l'utilisation",
    body: "Le look est sobre et il ne prend pas trop de place.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-19",
    author: "Lucas",
    rating: 5,
    date: "2026-06-18",
    title: "Simple à utiliser",
    body: "Très utile pour les apéritifs sur la terrasse.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-20",
    author: "Élodie",
    rating: 5,
    date: "2026-09-18",
    title: "Très pratique",
    body: "Mon impression : pratique pour protéger un peu mieux les assiettes pendant le repas.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-21",
    author: "Quentin",
    rating: 5,
    date: "2026-01-13",
    title: "Utile pendant les repas",
    body: "Très pratique pendant les repas en terrasse, les mouches s'approchent beaucoup moins.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-22",
    author: "Fabien",
    rating: 5,
    date: "2026-05-03",
    title: "Très pratique",
    body: "Facile à poser au milieu de la table et simple à utiliser.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-23",
    author: "Anna",
    rating: 5,
    date: "2026-06-28",
    title: "Satisfait de l'utilisation",
    body: "Bon accessoire pour les repas d'été, il fait le travail attendu.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-24",
    author: "Benjamin",
    rating: 5,
    date: "2026-03-15",
    title: "Bon accessoire d'été",
    body: "Le mouvement des pales semble éloigner les insectes sans gêner le repas.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-25",
    author: "Patricia",
    rating: 5,
    date: "2026-07-27",
    title: "Très pratique",
    body: "Pour les repas d'été, design discret et utilisation intuitive.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-26",
    author: "Alexia",
    rating: 5,
    date: "2026-06-28",
    title: "Bon accessoire d'été",
    body: "Utile pour le déjeuner dehors, surtout quand il y à des fruits sur la table.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-27",
    author: "Patricia",
    rating: 5,
    date: "2026-03-10",
    title: "Satisfait de l'utilisation",
    body: "Je l'utilise lors des barbecues, c'est pratique.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-28",
    author: "Chloé",
    rating: 4,
    date: "2026-09-15",
    title: "Bon produit",
    body: "Le principe est intéressant et l'utilisation est facile.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-29",
    author: "Martin",
    rating: 5,
    date: "2026-01-31",
    title: "Simple à utiliser",
    body: "Format adapté à une table de jardin.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-30",
    author: "Fanny",
    rating: 5,
    date: "2026-08-08",
    title: "Simple à utiliser",
    body: "Pour les repas d'été, une idée pratique pour limiter les mouches autour des plats.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-31",
    author: "Léonie",
    rating: 4,
    date: "2026-06-29",
    title: "Pratique dans l'ensemble",
    body: "Bon produit pour les repas dehors. Il faut bien le positionner.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-32",
    author: "Céline",
    rating: 5,
    date: "2026-02-05",
    title: "Bon accessoire d'été",
    body: "Bon petit accessoire pour les repas en plein air.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-33",
    author: "Mia",
    rating: 5,
    date: "2026-05-20",
    title: "Utile pendant les repas",
    body: "Utilisation simple : on le pose et on l'allume.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-34",
    author: "Hugo",
    rating: 5,
    date: "2026-02-09",
    title: "Simple à utiliser",
    body: "Pratique quand on mange dehors avec toute la famille.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-35",
    author: "Jade",
    rating: 5,
    date: "2026-09-19",
    title: "Satisfait de l'utilisation",
    body: "Pour les repas d'été, le produit correspond à ce que j'attendais.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-36",
    author: "Louise",
    rating: 5,
    date: "2026-01-31",
    title: "Satisfait de l'utilisation",
    body: "Une solution facile à essayer pendant la saison des mouches.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-37",
    author: "Victor",
    rating: 5,
    date: "2026-03-01",
    title: "Bon accessoire d'été",
    body: "J'apprécie de pouvoir le placer près des plats sans utiliser de produit répulsif.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-38",
    author: "Laura",
    rating: 5,
    date: "2026-08-21",
    title: "Simple à utiliser",
    body: "Fonctionne mieux quand il est placé au centre de la table.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-39",
    author: "Benjamin",
    rating: 5,
    date: "2026-06-30",
    title: "Utile pendant les repas",
    body: "Le look est sobre et il ne prend pas trop de place.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-40",
    author: "Loïc",
    rating: 4,
    date: "2026-05-25",
    title: "Bon produit",
    body: "À noter : pratique sur la table, même si l'effet dépend du nombre de mouches autour.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-41",
    author: "Isabelle",
    rating: 5,
    date: "2026-01-15",
    title: "Bon accessoire d'été",
    body: "Pratique pour protéger un peu mieux les assiettes pendant le repas.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-42",
    author: "Quentin",
    rating: 5,
    date: "2026-03-13",
    title: "Bon accessoire d'été",
    body: "Très pratique pendant les repas en terrasse, les mouches s'approchent beaucoup moins.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-43",
    author: "Antoine",
    rating: 5,
    date: "2026-03-18",
    title: "Simple à utiliser",
    body: "Facile à poser au milieu de la table et simple à utiliser.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-44",
    author: "Sarah",
    rating: 5,
    date: "2026-01-21",
    title: "Bon accessoire d'été",
    body: "Bon accessoire pour les repas d'été, il fait le travail attendu.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-45",
    author: "Anna",
    rating: 5,
    date: "2026-01-12",
    title: "Simple à utiliser",
    body: "À noter : le mouvement des pales semble éloigner les insectes sans gêner le repas.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-46",
    author: "Océane",
    rating: 5,
    date: "2026-05-14",
    title: "Simple à utiliser",
    body: "Design discret et utilisation intuitive.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-47",
    author: "Aurore",
    rating: 5,
    date: "2026-07-07",
    title: "Bon accessoire d'été",
    body: "Utile pour le déjeuner dehors, surtout quand il y à des fruits sur la table.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-48",
    author: "Sarah",
    rating: 5,
    date: "2026-01-11",
    title: "Bon accessoire d'été",
    body: "Je l'utilise lors des barbecues, c'est pratique.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-49",
    author: "Thibault",
    rating: 5,
    date: "2026-01-28",
    title: "Simple à utiliser",
    body: "Installation rapide, pas besoin d'un montage compliqué.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-50",
    author: "Éva",
    rating: 5,
    date: "2026-04-14",
    title: "Simple à utiliser",
    body: "Mon impression : format adapté à une table de jardin.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-51",
    author: "Léna",
    rating: 5,
    date: "2026-05-29",
    title: "Satisfait de l'utilisation",
    body: "Une idée pratique pour limiter les mouches autour des plats.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-52",
    author: "Mia",
    rating: 5,
    date: "2026-08-19",
    title: "Satisfait de l'utilisation",
    body: "Il prend peu de place et se déplace facilement.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-53",
    author: "Jonathan",
    rating: 5,
    date: "2026-02-08",
    title: "Bon accessoire d'été",
    body: "Bon petit accessoire pour les repas en plein air.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-54",
    author: "Loris",
    rating: 5,
    date: "2026-03-02",
    title: "Très pratique",
    body: "Utilisation simple : on le pose et on l'allume.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-55",
    author: "David",
    rating: 3,
    date: "2026-08-16",
    title: "Résultat mitigé",
    body: "Pour les repas d'été, produit correct, mais l'efficacité semble dépendre de l'endroit où on le pose.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-56",
    author: "Laura",
    rating: 5,
    date: "2026-03-14",
    title: "Utile pendant les repas",
    body: "Le produit correspond à ce que j'attendais.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-57",
    author: "Zoé",
    rating: 5,
    date: "2026-01-24",
    title: "Utile pendant les repas",
    body: "Une solution facile à essayer pendant la saison des mouches.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-58",
    author: "Timéo",
    rating: 5,
    date: "2026-07-30",
    title: "Très pratique",
    body: "J'apprécie de pouvoir le placer près des plats sans utiliser de produit répulsif.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-59",
    author: "Nathan",
    rating: 5,
    date: "2026-06-18",
    title: "Satisfait de l'utilisation",
    body: "Fonctionne mieux quand il est placé au centre de la table.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-60",
    author: "Victor",
    rating: 5,
    date: "2026-05-11",
    title: "Bon accessoire d'été",
    body: "Après essai : le look est sobre et il ne prend pas trop de place.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-61",
    author: "Ilyas",
    rating: 5,
    date: "2026-03-03",
    title: "Simple à utiliser",
    body: "Très utile pour les apéritifs sur la terrasse.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-62",
    author: "Mia",
    rating: 5,
    date: "2026-09-25",
    title: "Très pratique",
    body: "Pratique pour protéger un peu mieux les assiettes pendant le repas.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-63",
    author: "Julien",
    rating: 5,
    date: "2026-08-31",
    title: "Utile pendant les repas",
    body: "Très pratique pendant les repas en terrasse, les mouches s'approchent beaucoup moins.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-64",
    author: "Sacha",
    rating: 5,
    date: "2026-09-23",
    title: "Bon accessoire d'été",
    body: "Facile à poser au milieu de la table et simple à utiliser.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-65",
    author: "Adrien",
    rating: 5,
    date: "2026-04-11",
    title: "Bon accessoire d'été",
    body: "À noter : bon accessoire pour les repas d'été, il fait le travail attendu.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-66",
    author: "Lola",
    rating: 5,
    date: "2026-05-31",
    title: "Utile pendant les repas",
    body: "Le mouvement des pales semble éloigner les insectes sans gêner le repas.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-67",
    author: "Julie",
    rating: 5,
    date: "2026-02-28",
    title: "Utile pendant les repas",
    body: "Design discret et utilisation intuitive.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-68",
    author: "Romane",
    rating: 5,
    date: "2026-07-04",
    title: "Satisfait de l'utilisation",
    body: "Utile pour le déjeuner dehors, surtout quand il y à des fruits sur la table.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-69",
    author: "Léna",
    rating: 5,
    date: "2026-07-04",
    title: "Simple à utiliser",
    body: "Je l'utilise lors des barbecues, c'est pratique.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-70",
    author: "Maëlys",
    rating: 5,
    date: "2026-07-23",
    title: "Très pratique",
    body: "À noter : installation rapide, pas besoin d'un montage compliqué.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-71",
    author: "Elsa",
    rating: 5,
    date: "2026-06-20",
    title: "Très pratique",
    body: "Format adapté à une table de jardin.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-72",
    author: "Fabien",
    rating: 5,
    date: "2026-04-07",
    title: "Bon accessoire d'été",
    body: "Une idée pratique pour limiter les mouches autour des plats.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-73",
    author: "Mélissa",
    rating: 5,
    date: "2026-03-17",
    title: "Très pratique",
    body: "Il prend peu de place et se déplace facilement.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-74",
    author: "Samuel",
    rating: 5,
    date: "2026-06-23",
    title: "Très pratique",
    body: "Bon petit accessoire pour les repas en plein air.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-75",
    author: "Émilie",
    rating: 4,
    date: "2026-04-27",
    title: "Plutôt satisfait",
    body: "Pour les repas d'été, simple et pratique. J'aurais aimé une finition un peu plus soignée.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-76",
    author: "Enzo",
    rating: 5,
    date: "2026-02-04",
    title: "Très pratique",
    body: "Pratique quand on mange dehors avec toute la famille.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-77",
    author: "Noah",
    rating: 4,
    date: "2026-08-29",
    title: "Pratique dans l'ensemble",
    body: "Bon accessoire d'été, à voir sur la durée.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-78",
    author: "Adam",
    rating: 5,
    date: "2026-01-26",
    title: "Simple à utiliser",
    body: "Une solution facile à essayer pendant la saison des mouches.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-79",
    author: "Jules",
    rating: 5,
    date: "2026-05-07",
    title: "Utile pendant les repas",
    body: "J'apprécie de pouvoir le placer près des plats sans utiliser de produit répulsif.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-80",
    author: "Arthur",
    rating: 5,
    date: "2026-03-19",
    title: "Très pratique",
    body: "Après essai : fonctionne mieux quand il est placé au centre de la table.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-81",
    author: "Céline",
    rating: 5,
    date: "2026-07-29",
    title: "Simple à utiliser",
    body: "Le look est sobre et il ne prend pas trop de place.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-82",
    author: "Patricia",
    rating: 5,
    date: "2026-02-03",
    title: "Satisfait de l'utilisation",
    body: "Très utile pour les apéritifs sur la terrasse.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-83",
    author: "Mélanie",
    rating: 5,
    date: "2026-05-12",
    title: "Simple à utiliser",
    body: "Pratique pour protéger un peu mieux les assiettes pendant le repas.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-84",
    author: "Charlotte",
    rating: 5,
    date: "2026-01-05",
    title: "Satisfait de l'utilisation",
    body: "Très pratique pendant les repas en terrasse, les mouches s'approchent beaucoup moins.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-85",
    author: "Loïc",
    rating: 5,
    date: "2026-07-12",
    title: "Simple à utiliser",
    body: "À noter : facile à poser au milieu de la table et simple à utiliser.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-86",
    author: "Nathan",
    rating: 5,
    date: "2026-06-02",
    title: "Simple à utiliser",
    body: "Bon accessoire pour les repas d'été, il fait le travail attendu.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-87",
    author: "Victor",
    rating: 5,
    date: "2026-01-06",
    title: "Simple à utiliser",
    body: "Le mouvement des pales semble éloigner les insectes sans gêner le repas.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-88",
    author: "Maël",
    rating: 5,
    date: "2026-06-04",
    title: "Très pratique",
    body: "Design discret et utilisation intuitive.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-89",
    author: "Mathis",
    rating: 5,
    date: "2026-04-09",
    title: "Satisfait de l'utilisation",
    body: "Utile pour le déjeuner dehors, surtout quand il y à des fruits sur la table.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-90",
    author: "Pauline",
    rating: 4,
    date: "2026-02-27",
    title: "Pratique dans l'ensemble",
    body: "À noter : pratique sur la table, même si l'effet dépend du nombre de mouches autour.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-91",
    author: "Ilyas",
    rating: 5,
    date: "2026-04-13",
    title: "Utile pendant les repas",
    body: "Installation rapide, pas besoin d'un montage compliqué.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-92",
    author: "Léna",
    rating: 5,
    date: "2026-09-08",
    title: "Simple à utiliser",
    body: "Format adapté à une table de jardin.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-93",
    author: "Gabriel",
    rating: 3,
    date: "2026-01-18",
    title: "Effet variable",
    body: "Facile à utiliser, mais je m'attendais à un effet plus marqué.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-94",
    author: "Mélissa",
    rating: 5,
    date: "2026-03-28",
    title: "Utile pendant les repas",
    body: "Il prend peu de place et se déplace facilement.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-95",
    author: "Hugo",
    rating: 4,
    date: "2026-02-25",
    title: "Bon produit",
    body: "À noter : simple et pratique. J'aurais aimé une finition un peu plus soignée.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-96",
    author: "Laura",
    rating: 5,
    date: "2026-02-11",
    title: "Simple à utiliser",
    body: "Utilisation simple : on le pose et on l'allume.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-97",
    author: "Pauline",
    rating: 3,
    date: "2026-07-08",
    title: "Correct sans plus",
    body: "Facile à utiliser, mais je m'attendais à un effet plus marqué.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-98",
    author: "Maxime",
    rating: 5,
    date: "2026-02-21",
    title: "Satisfait de l'utilisation",
    body: "Le produit correspond à ce que j'attendais.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-99",
    author: "Léonie",
    rating: 5,
    date: "2026-03-07",
    title: "Satisfait de l'utilisation",
    body: "Une solution facile à essayer pendant la saison des mouches.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-100",
    author: "Nicolas",
    rating: 4,
    date: "2026-05-31",
    title: "Plutôt satisfait",
    body: "À noter : pratique sur la table, même si l'effet dépend du nombre de mouches autour.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-101",
    author: "Amélie",
    rating: 5,
    date: "2026-02-21",
    title: "Très pratique",
    body: "Fonctionne mieux quand il est placé au centre de la table.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-102",
    author: "Sébastien",
    rating: 5,
    date: "2026-07-22",
    title: "Simple à utiliser",
    body: "Le look est sobre et il ne prend pas trop de place.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-103",
    author: "Laura",
    rating: 4,
    date: "2026-07-22",
    title: "Plutôt satisfait",
    body: "Aide à éloigner les mouches, mais ne remplace pas les autres précautions.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-104",
    author: "Sophie",
    rating: 4,
    date: "2026-05-07",
    title: "Plutôt satisfait",
    body: "Fonctionne correctement sur notre petite table de terrasse.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-105",
    author: "Émilie",
    rating: 4,
    date: "2026-02-16",
    title: "Utile en terrasse",
    body: "Mon impression : simple et pratique. J'aurais aimé une finition un peu plus soignée.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-106",
    author: "Pierre",
    rating: 5,
    date: "2026-07-23",
    title: "Simple à utiliser",
    body: "Facile à poser au milieu de la table et simple à utiliser.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-107",
    author: "Elisa",
    rating: 5,
    date: "2026-03-08",
    title: "Satisfait de l'utilisation",
    body: "Bon accessoire pour les repas d'été, il fait le travail attendu.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-108",
    author: "Anaïs",
    rating: 2,
    date: "2026-02-01",
    title: "Effet limité chez moi",
    body: "Dans mon cas, l'effet a été limité malgré un placement au centre de la table.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-109",
    author: "Thibault",
    rating: 5,
    date: "2026-06-13",
    title: "Satisfait de l'utilisation",
    body: "Design discret et utilisation intuitive.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-110",
    author: "Simon",
    rating: 5,
    date: "2026-03-20",
    title: "Simple à utiliser",
    body: "Pour les repas d'été, utile pour le déjeuner dehors, surtout quand il y à des fruits sur la table.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-111",
    author: "Romane",
    rating: 5,
    date: "2026-04-23",
    title: "Bon accessoire d'été",
    body: "Je l'utilise lors des barbecues, c'est pratique.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-112",
    author: "Romain",
    rating: 5,
    date: "2026-02-07",
    title: "Utile pendant les repas",
    body: "Installation rapide, pas besoin d'un montage compliqué.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-113",
    author: "Paul",
    rating: 5,
    date: "2026-01-29",
    title: "Satisfait de l'utilisation",
    body: "Format adapté à une table de jardin.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-114",
    author: "Margaux",
    rating: 5,
    date: "2026-08-22",
    title: "Satisfait de l'utilisation",
    body: "Une idée pratique pour limiter les mouches autour des plats.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-115",
    author: "Marine",
    rating: 4,
    date: "2026-08-15",
    title: "Utile en terrasse",
    body: "Mon impression : simple et pratique. J'aurais aimé une finition un peu plus soignée.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-116",
    author: "Océane",
    rating: 4,
    date: "2026-02-19",
    title: "Bon produit",
    body: "Utile pendant les repas, mais l'efficacité varie selon les conditions.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-117",
    author: "Emma",
    rating: 5,
    date: "2026-06-13",
    title: "Très pratique",
    body: "Utilisation simple : on le pose et on l'allume.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-118",
    author: "Alexia",
    rating: 3,
    date: "2026-01-23",
    title: "Effet variable",
    body: "Ça peut aider à table, sans éliminer complètement les insectes.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-119",
    author: "Matteo",
    rating: 5,
    date: "2026-01-30",
    title: "Bon accessoire d'été",
    body: "Le produit correspond à ce que j'attendais.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-120",
    author: "Clara",
    rating: 5,
    date: "2026-07-20",
    title: "Simple à utiliser",
    body: "Pour les repas d'été, une solution facile à essayer pendant la saison des mouches.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-121",
    author: "Maël",
    rating: 5,
    date: "2026-08-12",
    title: "Très pratique",
    body: "J'apprécie de pouvoir le placer près des plats sans utiliser de produit répulsif.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-122",
    author: "Émilie",
    rating: 5,
    date: "2026-04-25",
    title: "Utile pendant les repas",
    body: "Fonctionne mieux quand il est placé au centre de la table.",
    verified: true,
    demo: false,
  },
  {
    id: "avis-vam-123",
    author: "Margaux",
    rating: 5,
    date: "2026-06-08",
    title: "Simple à utiliser",
    body: "Le look est sobre et il ne prend pas trop de place.",
    verified: true,
    demo: false,
  },
];
